### ISSUE TITLE
how to use this nexus-exporter in kuberenetes

### ISSUE THREAD

**Issue by nandeeshb09** [ocadotechnology/nexus-exporter#7]
Hi ,

can you guys tel me ,how to use this in kubernetes?.

From image if we spin up pod and integrate with Prometheus?

**Comment by mikebryant** [comment]
You can do something like this:

```
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nexus
spec:
  serviceName: nexus
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      securityContext:
        fsGroup: 2000
      containers:
      - name: nexus3
        image: sonatype/nexus3:3.12.1
        ports:
        - containerPort: 8081
          name: web
        livenessProbe:
          httpGet:
            path: /
            port: web
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: web
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 6
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus-data-volume
      - name: nexus-exporter
        image: ocadotechnology/nexus-exporter
        env:
        - name: NEXUS_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nexus-credentials
              key: admin
              optional: true
        ports:
        - containerPort: 9184
          name: http-metrics
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: nexus-data-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nexus
  namespace: nexus
  labels:
    app: nexus
spec:
  selector:
    matchLabels:
      app: nexus
  endpoints:
  - port: http-metrics
    interval: 10s
```

(Note that's not a full example, it's missing the Secret, headless Service etc, but hopefully illustrates how to use it)
