### ISSUE TITLE
Nexus exporter not reporting metrics

### ISSUE THREAD

**Issue by kratos81** [ocadotechnology/nexus-exporter#9]
I was not able to install the nexus exporter.  This is the relevant section of the statefulset yaml 

```
 - name: nexus-exporter
          image: ocadotechnology/nexus-exporter
          env:
          - name: NEXUS_USERNAME
            value: "admin"
          - name: NEXUS_HOST
            value: "http://localhost:8081"
          - name: NEXUS_ADMIN_PASSWORD
            value: "<nexus password>"
          ports:
          - containerPort: 9184
            name: http-metrics
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
```

The serviceMonitor yaml is 

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nexus
  labels:
    app: nexus
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: nexus
  endpoints:
  - port: http-metrics
    interval: 10s

```

However , the log just shows the nexus container with a message "starting"  and nothing else.  

```
kubectl logs -f nexus-0 -c nexus-exporter                                                                            
starting...
```

It doesn't move past that.  Please let me know if there is anything Im missing.   The associated objects are 

- statefulset 
- serviceMonitor 
- service for statefulset 

Thanks
